# Generated by Django 3.0.8 on 2020-07-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=15)),
                ('gener', models.CharField(max_length=15)),
                ('sort', models.CharField(max_length=15)),
                ('img_url', models.CharField(max_length=500)),
                ('movie', models.CharField(max_length=30)),
                ('rating', models.CharField(max_length=10)),
                ('votes', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=15)),
                ('duration', models.CharField(max_length=10)),
                ('character', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('introduction', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSpan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
