# Generated by Django 3.0.8 on 2020-07-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DATASCRAP', '0002_timespan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timespan',
            name='Telugu_update_time',
            field=models.DateTimeField(),
        ),
    ]
