# Generated by Django 3.0.8 on 2020-07-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DATASCRAP', '0003_auto_20200716_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timespan',
            old_name='Telugu_update_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='timespan',
            name='id',
        ),
        migrations.AddField(
            model_name='timespan',
            name='language',
            field=models.CharField(default=0, max_length=15, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
